server:
  port: 9002

spring:
  # datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.234.56.182:3306/security_oauth?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

# mybatis
mybatis:
  type-aliases-package: com.lc.security.user.domain
  mapper-locations: classpath*:/mapper/*.xml
